# image will be published to ghcr.io/<user>/<name>
name: ublue-stoeps-nvidia
# description will be included in the image's metadata
description: My ublue image for my personal and working devices

base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 39 # latest is also supported if you want new updates ASAP

modules:
  - type: files
    files:
      - usr: /usr # copy static configurations

  - from-file: rpm-ostree.yml

  - from-file: default-flatpaks.yml

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
      - workarounds.sh
