type: fonts
fonts:
  nerd-fonts:
    - FiraCode # don't add "Nerd Font" suffix.
    - Hack
    - SourceCodePro
    - Terminus
    - JetBrainsMono
    - NerdFontsSymbolsOnly
  google-fonts:
    - Roboto
    - Open Sans
