type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/che/nerd-fonts/repo/fedora-%OS_VERSION%/che-nerd-fonts-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo
  - https://negativo17.org/repos/fedora-multimedia.repo
  - https://copr.fedorainfracloud.org/coprs/kylegospo/gnome-vrr/repo/fedora-%OS_VERSION%/kylegospo-gnome-vrr-fedora-%OS_VERSION%.repo
  # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
install:
  - alacritty
  - bat
  - dbus-x11
  - devpod
  - edk2-ovmf
  - epson-inkjet-printer-escpr
  - epson-inkjet-printer-escpr2
  - fd-find
  - firewall-config
  - fzf
  - gcc
  - gcc-c++
  - genisoimage
  - gnome-shell-extension-appindicator
  - gnome-shell-extension-blur-my-shell
  - gnome-shell-extension-dash-to-dock
  - gnome-shell-extension-gsconnect
  - gnome-shell-extension-logo-menu
  - guestfs-tools
  - iotop
  - isync
  - kernel-devel
  - kmod-v4l2loopback
  - libvirt
  - libvirt-nss
  - make
  - notmuch
  - pass
  - podman-compose
  - podman-plugins
  - podmansh
  - powerline-fonts
  - powertop
  - python3-libvirt
  - qemu
  - qemu-char-spice
  - qemu-device-display-virtio-gpu
  - qemu-device-display-virtio-vga
  - qemu-device-usb-redirect
  - qemu-img
  - qemu-system-x86-core
  - qemu-user-binfmt
  - qemu-user-static
  - stow
  - thinkfan
  - tmux
  - v4l2loopback
  - vdirsyncer
  - vim
  - virt-install
  - virt-manager
  - virt-viewer
  - zsh
remove:
  - firefox
  - firefox-langpacks
  - gnome-classic-session
  - gnome-initial-setup
  - gnome-shell-extension-apps-menu
  - gnome-shell-extension-background-logo
  - gnome-shell-extension-launch-new-instance
  - gnome-shell-extension-places-menu
  - gnome-shell-extension-window-list
  - gnome-software-rpm-ostree
  - gnome-system-monitor
  - gnome-terminal
  - gnome-terminal-nautilus
  - gnome-tour
  - htop
  - nvtop
